### ISSUE TITLE
Graceful Shutdown and Cleanup

### ISSUE THREAD

**Issue by ferstar** [riley-martin/gestures#13]
**Describe the bug**
Run gestures once and then Ctrl + C, and run again, it fails to start.

**Expected behavior**

Clean up UNIX socket files when the program exits abnormally or normally

**Comment by riley-martin** [comment]
Ok, I see that. I'll try to fix it shortly.

**Comment by riley-martin** [comment]
> Run gestures once and then Ctrl + C, and run again, it fails to start.

For now, manually removing the socket (probably at `/run/user/1000/gestures.sock`) will fix the issue.

**Comment by riley-martin** [comment]
Merged some basic cleanup support in main. I think there could be a nicer solution, but it works so I'll close this issue.  

BTW sorry for the late reply.
