### ISSUE TITLE
Cannot run as non-root user

### ISSUE THREAD

**Issue by yyy33** [riley-martin/gestures#15]
**Describe the bug**
Cannot run as non-root user

**To Reproduce**
run as non-root user

**Expected behavior**
If it is not possible to run the program as normal it should exit on its own and prompt the user to use root.

**Comment by riley-martin** [comment]
To run the program, your user will likely need to be in the input group. You can add it like this:  
`sudo usermod -aG input yourusername`

**Comment by yyy33** [comment]
> To run the program, your user will likely need to be in the input group. You can add it like this: `sudo usermod -aG input yourusername`

It's working fine, thank you
