### ISSUE TITLE
Slide gestures being in conflict with hold gestures

### ISSUE THREAD

**Issue by yyy33** [riley-martin/gestures#17]
**Describe the bug**
In my configuration, the swipe gesture is never triggered, and when I swipe two fingers down, the hold action is triggered.

**Configuration**
```
swipe direction="s" fingers=2 end="mkdir -p /tmp/gg/swipe_start"
pinch direction="in" fingers=2 end="mkdir -p /tmp/gg/pinch_start"
hold fingers=2 action="mkdir -p /tmp/gg/hold"

```

**Comment by riley-martin** [comment]
That is because the desktop environment/apps recognize a 2 finger swipe as scrolling, which prevents other programs from properly recognizing it as a gesture. Using 3 or 4 finger gestures would probably work better.

**Comment by yyy33** [comment]
> That is because the desktop environment/apps recognize a 2 finger swipe as scrolling, which prevents other programs from properly recognizing it as a gesture. Using 3 or 4 finger gestures would probably work better.

https://github.com/riley-martin/gestures/issues/18#issuecomment-1933765165

**Comment by yyy33** [comment]
> That is because the desktop environment/apps recognize a 2 finger swipe as scrolling, which prevents other programs from properly recognizing it as a gesture. Using 3 or 4 finger gestures would probably work better.

You're right, I've seen linbinput documentation that says it takes more than 2 fingers to trigger the slide
