### ISSUE TITLE
Unable to control cursor

### ISSUE THREAD

**Issue by yyy33** [riley-martin/gestures#18]
**Describe the bug**
Is this to be expected?

**Configuration**

swipe direction="s" fingers=2 end="mkdir -p /tmp/gg/swipe_start"
pinch direction="in" fingers=2 end="mkdir -p /tmp/gg/pinch_start"
hold fingers=2 action="mkdir -p /tmp/gg/hold"

**Comment by riley-martin** [comment]
I'm not quite sure what the problem is, could you explain what is happening? One problem could be using 2 fingers for swipe gestures, the desktop environment and apps use this for scrolling.

**Comment by yyy33** [comment]
> could you explain what is happening
What I mean is that when I use one finger to move on the touchpad, the mouse cursor in the screen does not follow my finger!

**Comment by yyy33** [comment]
> One problem could be using 2 fingers for swipe gestures, the desktop environment and apps use this for scrolling.

But I've turned off Xorg's Libinput's capture of touchpad events as per your doc.

/usr/share/X11/xorg.conf.d/99-ignore-device.conf
````
But I've turned off Xorg's Libinput's capture of touchpad events as per your doc.
````

**Comment by yyy33** [comment]
I read the code for gestures, is it because gestures doesn't handle `input::event::pointer::PointerEvent`? I'm not sure.
https://github.com/riley-martin/gestures/blob/a6447d422b8fd6ca45b0991af49c33c6b7c13871/src/event_handler.rs#L94

**Comment by yyy33** [comment]
> the desktop environment and apps use this for scrolling.

Also I don't use any other desktop environments besides xorg and awesome wm

**Comment by riley-martin** [comment]
>What I mean is that when I use one finger to move on the touchpad, the mouse cursor in the screen does not follow my finger. 

That is because you told x11 to ignore your device. Libinput recognizes different types of events; moving the cursor and scrolling are different from multi-touch gestures. To make this tool work properly, you should disable multi-touch events but not totally ignore the device.  

I'm not familiar with your setup so I can't tell you how to do this, but the setting is probably in the awesomewm configuration rather that in the x11 configuration.

**Comment by yyy33** [comment]
> > What I mean is that when I use one finger to move on the touchpad, the mouse cursor in the screen does not follow my finger.
> 
> That is because you told x11 to ignore your device. Libinput recognizes different types of events; moving the cursor and scrolling are different from multi-touch gestures. To make this tool work properly, you should disable multi-touch events but not totally ignore the device.
> 
> I'm not familiar with your setup so I can't tell you how to do this, but the setting is probably in the awesomewm configuration rather that in the x11 configuration.

I was able to get it working again today, I'm guessing it might have been because I added the user to the input group

**Comment by yyy33** [comment]
> > What I mean is that when I use one finger to move on the touchpad, the mouse cursor in the screen does not follow my finger.
> 
> That is because you told x11 to ignore your device. Libinput recognizes different types of events; moving the cursor and scrolling are different from multi-touch gestures. To make this tool work properly, you should disable multi-touch events but not totally ignore the device.
> 
> I'm not familiar with your setup so I can't tell you how to do this, but the setting is probably in the awesomewm configuration rather that in the x11 configuration.

Tankyou for help
