### ISSUE TITLE
Any plan to implement three-finger dragging?

### ISSUE THREAD

**Issue by ferstar** [riley-martin/gestures#4]
As a former macOS user, I miss the three-finger dragging feature.

I found that this [repo](https://github.com/marsqing/libinput-three-finger-drag) has already implemented that feature but still parse `libinput debug-events` rather than using libinput api

Can you refer to it and make a similar feature? thanks a lot!

**Comment by riley-martin** [comment]
I haven't used macOS, so I didn't think of doing something like that; however, it could be a
nice feature to have.  
Basically if you drag with three fingers over a 'draggable' target, it picks it up and moves
it, correct?

**Comment by ferstar** [comment]
Yes, that's exactly right!
The feature can help people easily select text or drag something around
